# Generated by Django 4.2.3 on 2023-07-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_shoe_colorway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='model',
            new_name='modelName',
        ),
    ]
