# Generated by Django 4.2.3 on 2023-07-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_model_shoe_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='img',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
