# Generated by Django 4.2.3 on 2023-07-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_shoe_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='type',
            field=models.CharField(choices=[('boots', 'Boots'), ('sneakers', 'Sneakers'), ('casual', 'Casual'), ('athletic', 'Athletic')], default=('sneakers', 'Sneakers'), max_length=50),
        ),
    ]
