# Generated by Django 4.2.3 on 2023-07-09 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_alter_shoe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='modelName',
            field=models.CharField(max_length=100, verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='type',
            field=models.CharField(choices=[('Sneakers', 'Sneakers'), ('Casual', 'Casual'), ('Boots', 'Boots'), ('Athletic', 'Athletic')], default='Sneakers', max_length=20),
        ),
    ]
