# Generated by Django 4.2.3 on 2023-07-09 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0010_shoe_user_alter_shoe_modelname_alter_shoe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_shoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
