# Generated by Django 4.2.3 on 2023-07-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_shoe_followers_remove_shoe_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='comments',
            field=models.TextField(default='Great', max_length=140),
            preserve_default=False,
        ),
    ]
