# Generated by Django 4.2.3 on 2023-07-11 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0014_shoe_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='comments',
        ),
        migrations.AddField(
            model_name='shoe',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
