# Generated by Django 4.2.3 on 2023-07-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_shoe_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
